CPPFLAGS:=-pedantic-errors -Wall
INC:=-I "../include/" -I "../inc"
LNK:=-L "../lib" -lmingw32 -lSDL2main -lSDL2
SRC:=$(wildcard src/*.cpp)
OBJ:=$(SRC:.cpp=.o)

bin/a.out: $(OBJ)
	g++ $^ -o $@ $(LNK)

src/main.o: src/main.cpp

%.o: %.cpp
	g++ $(INC) $(CPPFLAGS) $< -c -o $@
